# Generated by Django 3.0.3 on 2020-02-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
